$list = "Chris Polaski", 
"Troy Flick", 
"Ryan Kane", 
"Leah Crowe", 
"Micah Dietz", 
"Alan Herrera", 
"Rachel Whitehill", 
"Alexander Chan", 
"Stephen Placido", 
"Maira Vega", 
"Veronica Rodriguez", 
"Cate Waligora", 
"Lindsay Suprenant", 
"Jonathan Zhou", 
"Mohammad Hatahet", 
"Erika Sanchez", 
"Zach Motsinger", 
"Johnny Betzer", 
"Niraj Patel", 
"Tami Green", 
"Genaro Mendoza", 
"Luis Rodriguez", 
"Diana Melendez", 
"Chelsea Chamra", 
"Michele Olivo", 
"Delia Farrell", 
"Zach Barton", 
"Efren Murillo", 
"Ben Blakeman", 
"Martin Camacho", 
"Ramon Salcido", 
"Marek Pula", 
"Andrew Lee", 
"Erik Randa", 
"Rob Kiester", 
"Kevin Strohfus", 
"Isaac Sawatzky", 
"Sara Ruiz", 
"Kelsey Grundman", 
"Ryan Bullock", 
"Vassanti Bribiesca", 
"Patricia Valero", 
"Saatchi Kishnani", 
"Callie Bergin"

$a = Get-ADUser -Filter * 

foreach ($user in $list){
    $Splitname =$user -split " "
    $a | Where-Object {($_.GivenName -eq $SplitName[0]) -and ($_.Surname -eq $splitName[1])} | select samaccountname
}
