Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install 7zip -y
choco install GoogleChrome -y               
choco install notepadplusplus -y
choco install vlc -y
choco install Firefox -y
#choco install vmware-powercli-psmodule  -y
#choco install winscp                    -y
#choco install wintail                   -y
#choco install wireshark                 -y
#choco install Dashlane                  -y
#choco install Dashlane-chrome           -y
#choco install Silverlight               -y
#choco install github-desktop            -y
#choco install sql-server-management-studio -y
#choco install iperf3                    -y
#choco install lastpass-chrome           -y
#choco install putty                     -y
#choco install rdcman                    -y
#choco install rsat                      -y
#choco install rufus                     -y
#choco install snmpb                     -y
#choco install sysinternals              -y
#choco install visualstudio2017community -y
#choco install nmap    -y
#choco install autohotkey                -y
#choco install Firefox                   -y
